# Do not edit this file.

source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib', '~> 1.4.7'

gem 'activesupport'

gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'

gem "minitest-rg"

gem "dotenv"

gem "rake"
gem 'simplecov', :require => false, :group => :test

gem 'rubocop', '~> 0.37.2', require: false
gem 'inch', require: false