# Do not edit this file.

# This is the main application script. To run your web server (which you
# need to do before you can see your website in a browser), you would run
# `ruby main.rb` in Terminal.

# These lines invoke a tool call Bundler to automatically `require` several
# Ruby scripts that make this Web framework work.
require 'rubygems'
require 'bundler'
Bundler.require

require 'dotenv'
Dotenv.load

# This is an add-on to the Web framework, which scans your code anew each time
# you save it. Otherwise, you would have to `Control + C` to stop the server
# and then run it again--each time you changed your code.
require 'sinatra/reloader'

# This sets up a class called MyApp, which you will use in controllers.
require 'sinatra/base'
class MyApp < Sinatra::Base
  register Sinatra::ActiveRecordExtension
  register Sinatra::Reloader
  set :sessions, true
  set :bind, '0.0.0.0'
  set :show_exceptions, true
  set :views, Proc.new { File.join(root, "app", "views") }
end
require 'sinatra/activerecord'
require './config/environments'

def database_exists?
  ActiveRecord::Base.connection rescue ActiveRecord::NoDatabaseError ? false : true
end

if database_exists?
  require_relative "db/define_schema"
  schema_file = File.open('db/schema.rb', 'w')
  ActiveRecord::SchemaDumper.dump ActiveRecord::Base.connection, schema_file
  schema_file.close
else
  puts "Please run the bin/setup command again."
  puts "You might see warnings that the databases already exist. That is OK."
  puts "But if you keep seeing this message, then ask for help."
end

require_relative "./config/_uploader.rb"

require 'tilt/erb'

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

Dir[File.dirname(__FILE__) + '/app/models/*.rb'].each {|file| require file }

Dir[File.dirname(__FILE__) + '/app/controllers/*.rb'].each {|file| require file }